# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/Svirusx/Nethunter-Kernel-S20_FE_5G.git
          #kernel-dir: msm-4.19
          kernel-branch: nethunter-13.0
          config: wirus_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: false
          ksu-version: main
          android-version: 12
          aosp-clang-version: r450784d
          disable-lto: true
          anykernel3: false

